name: Publish @jchpro/ngx-common to NPM
on:
  push:
    tags:
      - 'common-*'

permissions:
  contents: read

jobs:
  publish:
    name: Build and stage publish @jchpro/ngx-common
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build common library
        run: npm run build:common:prod
      - name: Stage publish common library
        working-directory: ./dist/@jchpro/ngx-common
        run: npm stage publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
